load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "Loopback",
    sketch = "Loopback.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_transport"],
)
